---
- name: Install Shavian Fonts
  hosts: localhost
  connection: local
  gather_facts: true
    
  vars:
    fonts_source_dir: "{{ playbook_dir }}"
    fonts_dest_dir: "{{ ansible_env.HOME }}/.local/share/fonts"
  
  tasks:
    - name: Check if fonts directory exists
      stat:
        path: "{{ fonts_source_dir }}"
      register: fonts_dir
      
    - name: Fail if fonts directory not found
      fail:
        msg: "Fonts directory not found at {{ fonts_source_dir }}"
      when: not fonts_dir.stat.exists
      
    - name: Create user fonts directory
      file:
        path: "{{ fonts_dest_dir }}"
        state: directory
        mode: '0755'
        
    - name: Find all font subdirectories
      find:
        paths: "{{ fonts_source_dir }}"
        file_type: directory
        depth: 1
      register: font_subdirs
      
    - name: Copy font directories
      copy:
        src: "{{ item.path }}/"
        dest: "{{ fonts_dest_dir }}/{{ item.path | basename }}/"
        mode: '0644'
        directory_mode: '0755'
      loop: "{{ font_subdirs.files }}"
      when: font_subdirs.files | length > 0
      
    - name: Find all font files in subdirectories
      find:
        paths: "{{ fonts_dest_dir }}"
        patterns: "*.otf,*.ttf"
        recurse: true
      register: installed_fonts
      
    - name: Set proper permissions on font files
      file:
        path: "{{ item.path }}"
        mode: '0644'
      loop: "{{ installed_fonts.files }}"
      
    - name: Update font cache
      command: fc-cache -fv {{ fonts_dest_dir }}
      register: fc_cache_result
      changed_when: true
      
    - name: Show installation results
      debug:
        msg: 
          - "✓ Font installation complete!"
          - "Installed {{ installed_fonts.files | length }} font files"
          - "Fonts copied to: {{ fonts_dest_dir }}"
          
    - name: List installed font directories
      debug:
        msg: "Installed font families: {{ font_subdirs.files | map(attribute='path') | map('basename') | list }}"
      when: font_subdirs.files | length > 0